map22 (skipped 40, 42, 55, 57)
OfficialLayton/Captured-Als-To-Romeria-Translation pull request #26
Opened 2023-01-22 22:19 UTC by carrotcake227

2023-01-29 22:12 UTC, OfficialLayton requested changes
Sorry for taking so long on the review Carrot! Thanks again for your help!
Just a slight translation change request and editing those commas back in would be great.

After those are done I'd be happy to approve. Thanks again ^^

2023-01-29 22:12 UTC, OfficialLayton commented on Translation Script/Map107.csv
> +おちんちんにきちゃうでしょ♥","\n<Lily>Those levels of yours...
Ditto for this translation too ^^

2023-01-29 22:12 UTC, OfficialLayton commented on Translation Script/Map107.csv
> +"読んでみる",Read
Oh dear, we can't have this. If we remove the commas like this, the csv will break!

That wouldn't be good at all. Definitely go through and fix these if you can haha

2023-01-29 22:12 UTC, OfficialLayton commented on Translation Script/Map107.csv
> +"調味料・・・",Spices...
Ditto commas for this.

2023-01-29 22:12 UTC, OfficialLayton commented on Translation Script/Map107.csv
> -"麦・・・","Flour..."
Commas.

2023-01-29 22:12 UTC, OfficialLayton commented on Translation Script/Map107.csv
> -"アイテム","Items"
Commas.

2023-02-07 20:03 UTC, carrotcake227 commented
Sorry for the delay! School is picking up for me again and I was having trouble with git which kind of demotivated me to work on this haha. I'll try to get through more of it soon. 

Also, when you said commas, did you mean quotation marks? That's what I interpreted it as.

2023-02-13 06:41 UTC, OfficialLayton approved these changes

2023-02-15 05:41 UTC, OfficialLayton requested changes

2023-02-15 05:41 UTC, OfficialLayton commented on Translation Script/Map107.csv
> +"リラクゼーションの本だ・・・",A book on relaxation...
More missing quotation marks here too!

2023-02-15 05:41 UTC, OfficialLayton commented on Translation Script/Map107.csv
> +"カチコチに凍っている・・・",It's frozen solid...
Here as well!

2023-02-15 05:44 UTC, OfficialLayton commented
Hello @carrotcake227! 

I am very, very sorry for the late reply, I've been busy myself so I can totally understand. Wishing you all the best for your school stuffs! Once again, thank you very, very much for your help. I can't thank you enough! And please, feel free to go at your own pace.  If you're having any more trouble with git in the future let me know and I'd be happy to help. It's the least I can do ^^
Ack, you're totally right. I did mean the quotation marks! Basically without them the csvs will be read incorrectly.

For example: 
`"カチコチに凍っている・・・",It's frozen solid...`
Should be:
`"カチコチに凍っている・・・","It's frozen solid..."`

I did still seem some more cases of missing quotation marks, did you manage to get them all?

2023-02-19 03:17 UTC, OfficialLayton commented
Looks good to me!

Sorry about the lateness in getting this merged. Hopefully nothing breaks and thank you very, very much Carrot! Much appreciated ^^

2023-02-19 03:18 UTC, OfficialLayton commented
Ah, sorry my bad @carrotcake227 it appears there are some merge conflicts, let me know once they're done and I'll merge after that ^^

2023-03-05 10:42 UTC, merged

2023-03-05 10:44 UTC, OfficialLayton commented
Heyo @carrotcake227!

Sorry about the late reply, I know you're busy, so I had a look at the merge conflicts and they *seem* to be just from the comma error that happened recently. I've done my best to resolve them myself so you don't have to worry about it ^^

With this, I should be able to just merge what you've done into the translation! Thanks again for your help :D